# Generated by Django 6.0.4 on 2026-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default=5000, max_length=100),
            preserve_default=False,
        ),
    ]
